version: "3.5"

services:
  welup-supernode:
    image: docker.pkg.github.com/clownsss/java-tron/welupchain:dev
    networks:
      welupnetwork:
        ipv4_address: 172.18.0.2
    ports:
      - "16666-16669:16666-16669/tcp"
      - "16666-16669:16666-16669/udp"
    volumes:
      - ./nodes/supernode:/node
    command:
      - --witness
  welup-fullnode:
    image: docker.pkg.github.com/clownsss/java-tron/welupchain:dev
    networks:
      welupnetwork:
        ipv4_address: 172.18.0.3
    ports:
      - "17666-17669:17666-17669/tcp"
      - "17666-17669:17666-17669/udp"
    volumes:
      - ./nodes/fullnode:/node

networks:
  welupnetwork:
    name: welupnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
